/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Avion;
import domain.Avioprevoznik;
import domain.Destinacija;
import domain.DomainObject;
import domain.Korisnik;
import domain.Let;
import gui.components.LetTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import komunikacija.KomunikacijaSaServerom;
import threads.OsveziKorisnikTabeluLetovaNit;

/**
 *
 * @author dejanmilovanovic
 */
public class GlavnaKlijentskaForma extends javax.swing.JFrame {

    private final Korisnik korisnik;

    /**
     * Creates new form GlavnaKlijentskaForma
     */
    public GlavnaKlijentskaForma(Korisnik k) {
        initComponents();
        setLocationRelativeTo(null);
        this.korisnik = k;
        OsveziKorisnikTabeluLetovaNit osveziNit = new OsveziKorisnikTabeluLetovaNit(this);
        try {
            fillComboBoxes();
            srediTabelu();
            osveziNit.start();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom popunjavanja podataka!");
            Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                if (osveziNit != null) {
                    osveziNit.terminate();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLetovi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbPolaznaDestinacija = new javax.swing.JComboBox();
        cmbKrajnjaDestinacija = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatumPolaska = new javax.swing.JTextField();
        txtDatumPovratka = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbAvioprevoznik = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        btnRezervisi = new javax.swing.JButton();
        btnSveRezervacije = new javax.swing.JButton();
        btnPonistiFiltere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Korisnička forma");

        tblLetovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLetovi);

        jLabel2.setText("Letovi u ponudi:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraži letove"));

        cmbPolaznaDestinacija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbKrajnjaDestinacija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Polazna destinacija");

        jLabel3.setText("Krajnja destinacija");

        txtDatumPolaska.setText("dd/MM/yyyy");

        txtDatumPovratka.setText("dd/MM/yyyy");

        jLabel4.setText("Datum polaska");

        jLabel5.setText("Datum povratka");

        cmbAvioprevoznik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Avioprevoznik");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPolaznaDestinacija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbKrajnjaDestinacija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDatumPolaska)
                    .addComponent(txtDatumPovratka)
                    .addComponent(cmbAvioprevoznik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPolaznaDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbKrajnjaDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatumPovratka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAvioprevoznik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPretrazi)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnRezervisi.setText("Rezerviši");
        btnRezervisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezervisiActionPerformed(evt);
            }
        });

        btnSveRezervacije.setText("Pogledaj sve rezervacije");
        btnSveRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSveRezervacijeActionPerformed(evt);
            }
        });

        btnPonistiFiltere.setText("Poništi filtere");
        btnPonistiFiltere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiFiltereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRezervisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSveRezervacije)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPonistiFiltere)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRezervisi)
                    .addComponent(btnSveRezervacije)
                    .addComponent(btnPonistiFiltere))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSveRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSveRezervacijeActionPerformed
        JDialog rezDialog = new RezervacijeKorisnikaDialog(this, true, korisnik);
        rezDialog.setVisible(true);
    }//GEN-LAST:event_btnSveRezervacijeActionPerformed

    private void btnRezervisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezervisiActionPerformed
        int row = tblLetovi.getSelectedRow();
        if (row != -1) {
            LetTableModel ltm = (LetTableModel) tblLetovi.getModel();
            Let let = (Let) ltm.getLetovi().get(row);
            RezervacijaDialog rd = new RezervacijaDialog(this, true, let, korisnik);
            rd.setVisible(true);
//            setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite let za koji želite da rezervišete kartu!");
        }
    }//GEN-LAST:event_btnRezervisiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {

            Destinacija polaznaDestinacija = (Destinacija) cmbPolaznaDestinacija.getSelectedItem();
            Destinacija krajnjaDestinacija = (Destinacija) cmbKrajnjaDestinacija.getSelectedItem();
            Date datumPolaska = null;
            Date datumPovratka = null;
            if (!"dd/MM/yyyy".equals(txtDatumPolaska.getText()) && !"".equals(txtDatumPolaska.getText())) {
                datumPolaska = new SimpleDateFormat("dd/MM/yyyy").parse(txtDatumPolaska.getText());
            }
            if (!"dd/MM/yyyy".equals(txtDatumPovratka.getText()) && !"".equals(txtDatumPovratka.getText())) {
                datumPovratka = new SimpleDateFormat("dd/MM/yyyy").parse(txtDatumPovratka.getText());
            }

            Avioprevoznik avioprevoznik = (Avioprevoznik) cmbAvioprevoznik.getSelectedItem();
            Avion avion = new Avion(-1, avioprevoznik, "");

            Let letPretraga = new Let(-1, datumPolaska, datumPovratka, 0, BigDecimal.ONE, polaznaDestinacija, krajnjaDestinacija, avion);

            LinkedList<DomainObject> letovi = KomunikacijaSaServerom.getInstanca().pronadjiLetove(letPretraga);

            LetTableModel tm = new LetTableModel();
            tblLetovi.setModel(tm);

            if (letovi.isEmpty()) {
                tm.setLetovi(letovi);
                throw new Exception("Nijedan let nije pronađen!");
            }

            tm.setLetovi(letovi);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Neispravan format datuma! (dd/MM/yyyy)");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(GlavnaAdminForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPonistiFiltereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiFiltereActionPerformed
        try {
            osvezi();
            txtDatumPolaska.setText("dd/MM/yyyy");
            txtDatumPovratka.setText("dd/MM/yyyy");
        } catch (Exception ex) {
            Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPonistiFiltereActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPonistiFiltere;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnRezervisi;
    private javax.swing.JButton btnSveRezervacije;
    private javax.swing.JComboBox cmbAvioprevoznik;
    private javax.swing.JComboBox cmbKrajnjaDestinacija;
    private javax.swing.JComboBox cmbPolaznaDestinacija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLetovi;
    private javax.swing.JTextField txtDatumPolaska;
    private javax.swing.JTextField txtDatumPovratka;
    // End of variables declaration//GEN-END:variables

    private void fillComboBoxes() throws Exception {
        LinkedList<DomainObject> destinacije = KomunikacijaSaServerom.getInstanca().vratiDestinacije();
        LinkedList<DomainObject> avioprevoznici = KomunikacijaSaServerom.getInstanca().vratiAvioprevoznike();
        cmbPolaznaDestinacija.removeAllItems();
        cmbKrajnjaDestinacija.removeAllItems();
        cmbAvioprevoznik.removeAllItems();

        cmbPolaznaDestinacija.addItem(new Destinacija(-1, "Sve destinacije"));
        for (DomainObject polaznaDestinacija : destinacije) {
            cmbPolaznaDestinacija.addItem(polaznaDestinacija);
        }
        cmbKrajnjaDestinacija.addItem(new Destinacija(-1, "Sve destinacije"));
        for (DomainObject krajnjaDestinacija : destinacije) {
            cmbKrajnjaDestinacija.addItem(krajnjaDestinacija);
        }
        cmbAvioprevoznik.addItem(new Avioprevoznik(-1, "Svi"));
        for (DomainObject avioprevoznik : avioprevoznici) {
            cmbAvioprevoznik.addItem(avioprevoznik);
        }
    }

    public void fillTable() throws Exception {
        LinkedList<DomainObject> letovi = KomunikacijaSaServerom.getInstanca().vratiLetove();
        LetTableModel tm = (LetTableModel) tblLetovi.getModel();
        tm.setLetovi(letovi);
    }

    void osvezi() throws Exception {
        fillTable();
        fillComboBoxes();
    }

    private void srediTabelu() {
        LetTableModel tm = new LetTableModel();
        tblLetovi.setModel(tm);
    }
}
