/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Avion;
import domain.Avioprevoznik;
import domain.Destinacija;
import domain.DomainObject;
import domain.Let;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;

/**
 *
 * @author dejanmilovanovic
 */
public class LetDialog extends javax.swing.JDialog {

    String status = "insert";
    Let let;
    GlavnaAdminForma parent;
    LinkedList<DomainObject> avioni;

    /**
     * Creates new form LetDialog
     */
    public LetDialog(GlavnaAdminForma parent, boolean modal, Let let) {
        super(parent, modal);
        
        try {
            this.parent = parent;
            initComponents();
            setLocationRelativeTo(parent);
            
            if (let != null) {
                this.let = let;
                this.status = "update";
                fillFieldsForUpdate();
            } else {
                fillFields();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška prilikom popunjavanja podataka!","Let dialog",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(LetDialog.class.getName()).log(Level.SEVERE, null, e);
        }

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                
            }
        });

        cmbAvioprevoznik.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                Avioprevoznik avioprevoznik = (Avioprevoznik) cmbAvioprevoznik.getSelectedItem();
                cmbAvion.removeAllItems();
                for (DomainObject avion : avioni) {
                    Avion domain = (Avion) avion;
                    if (domain.getAvioprevoznik().equals(avioprevoznik)) {
                        cmbAvion.addItem(domain);
                    }

                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDatumPolaska = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDatumPovratka = new javax.swing.JTextField();
        txtDuzinaLeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCenaLeta = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        cmbPolaznaDestinacija = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        cmbKrajnjaDestinacija = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        cmbAvioprevoznik = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        cmbAvion = new javax.swing.JComboBox();
        btnSačuvaj = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o letu"));

        jLabel1.setText("Datum polaska:");

        txtDatumPolaska.setText("dd/MM/YYYY");

        jLabel2.setText("Datum povratka:");

        txtDatumPovratka.setText("dd/MM/YYYY");

        jLabel3.setText("Dužina leta (min):");

        jLabel4.setText("Cena leta (RSD):");

        jLabel37.setText("Polazna destinacija");

        cmbPolaznaDestinacija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel38.setText("Krajnja destinacija");

        cmbKrajnjaDestinacija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel41.setText("Avioprevoznik");

        cmbAvioprevoznik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel42.setText("Avion");

        cmbAvion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSačuvaj.setText("Sačuvaj");
        btnSačuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSačuvajActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel42)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAvioprevoznik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKrajnjaDestinacija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPolaznaDestinacija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatumPolaska, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDatumPovratka)
                            .addComponent(txtDuzinaLeta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCenaLeta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbAvion, 0, 192, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSačuvaj)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cmbPolaznaDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cmbKrajnjaDestinacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatumPovratka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDuzinaLeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCenaLeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(cmbAvioprevoznik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(cmbAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSačuvaj)
                    .addComponent(btnOtkazi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSačuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSačuvajActionPerformed
        try {
            Destinacija polaznaDestinacija = (Destinacija) cmbPolaznaDestinacija.getSelectedItem();
            Destinacija krajnjaDestinacija = (Destinacija) cmbKrajnjaDestinacija.getSelectedItem();
            Date datumPolaska = new SimpleDateFormat("dd/MM/yyyy").parse(txtDatumPolaska.getText());
            Date datumPovratka = new SimpleDateFormat("dd/MM/yyyy").parse(txtDatumPovratka.getText());
            int duzinaLeta = Integer.parseInt(txtDuzinaLeta.getText());
            BigDecimal cenaLeta = new BigDecimal(txtCenaLeta.getText());
            Avion avion = (Avion) cmbAvion.getSelectedItem();

            Let l = new Let(-1, datumPolaska, datumPovratka, duzinaLeta, cenaLeta, polaznaDestinacija, krajnjaDestinacija, avion);

            if (status.equals("insert")) {
                l = KomunikacijaSaServerom.getInstanca().dodajLet(l);
                if (l.getLetID() != -1) {
                    JOptionPane.showMessageDialog(this, "Let je uspešno unet!","Unos leta",JOptionPane.INFORMATION_MESSAGE);
                    parent.osvezi();
//                    parent.setEnabled(true);
                    dispose();
                }
            } else {
                long idLeta = let.getLetID();
                l.setLetID(idLeta);
                l = KomunikacijaSaServerom.getInstanca().izmeniLet(l);
                parent.osvezi();
                JOptionPane.showMessageDialog(this, "Sistem je izmenio let!","Izmena leta",JOptionPane.INFORMATION_MESSAGE);
//                parent.setEnabled(true);
                dispose();
            }
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Numerička polja ne smeju biti prazna!","Let dialog",JOptionPane.ERROR_MESSAGE);
        }catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Neispravan format datuma!","Let dialog",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom popunjavanja polja!","Let dialog",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(LetDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Let dialog",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(LetDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSačuvajActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSačuvaj;
    private javax.swing.JComboBox cmbAvion;
    private javax.swing.JComboBox cmbAvioprevoznik;
    private javax.swing.JComboBox cmbKrajnjaDestinacija;
    private javax.swing.JComboBox cmbPolaznaDestinacija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCenaLeta;
    private javax.swing.JTextField txtDatumPolaska;
    private javax.swing.JTextField txtDatumPovratka;
    private javax.swing.JTextField txtDuzinaLeta;
    // End of variables declaration//GEN-END:variables

    private void fillFields() throws IOException, Exception  {
        LinkedList<DomainObject> destinacije = KomunikacijaSaServerom.getInstanca().vratiDestinacije();
        LinkedList<DomainObject> avioprevoznici = KomunikacijaSaServerom.getInstanca().vratiAvioprevoznike();
        this.avioni = KomunikacijaSaServerom.getInstanca().vratiAvione();
        cmbPolaznaDestinacija.removeAllItems();
        cmbKrajnjaDestinacija.removeAllItems();
        cmbAvioprevoznik.removeAllItems();
        cmbAvion.removeAllItems();

        for (DomainObject polaznaDestinacija : destinacije) {
            cmbPolaznaDestinacija.addItem(polaznaDestinacija);
        }
        
        for (DomainObject krajnjaDestinacija : destinacije) {
            cmbKrajnjaDestinacija.addItem(krajnjaDestinacija);
        }
        for (DomainObject avioprevoznik : avioprevoznici) {
            cmbAvioprevoznik.addItem(avioprevoznik);
        }

        for (DomainObject avion : avioni) {
            Avion domain = (Avion) avion;
            if (domain.getAvioprevoznik().equals(avioprevoznici.getFirst())) {
                cmbAvion.addItem(domain);
            }

        }

    }

    private void fillFieldsForUpdate() throws Exception {
        fillFields();
        
        this.let = KomunikacijaSaServerom.getInstanca().vratiLet(let);
        cmbPolaznaDestinacija.setSelectedItem(let.getLetOd());
        cmbKrajnjaDestinacija.setSelectedItem(let.getLetDo());
        cmbAvioprevoznik.setSelectedItem(let.getAvion().getAvioprevoznik());

        //Dodavanje odgovarajuće liste aviona u zavisnosti od avioprevoznika i setovanje Aviona
        cmbAvion.removeAllItems();
        for (DomainObject avion : avioni) {
            Avion domain = (Avion) avion;
            if (domain.getAvioprevoznik().equals(let.getAvion().getAvioprevoznik())) {
                cmbAvion.addItem(domain);
            }

        }

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        txtDatumPolaska.setText(format.format(let.getDatumPolaska()));
        txtDatumPovratka.setText(format.format(let.getDatumPovratka()));
        txtDuzinaLeta.setText(let.getDuzinaLeta() + "");
        txtCenaLeta.setText(let.getCenaLeta() + "");

    }

}
